### ISSUE TITLE
Wrong augment statement

### ISSUE THREAD

**Issue by michbin** [openBackhaul/lldp#4]
Revision 2023-05-24 of the lldp-1-0 model augments `equipment-augment:protocol` under the following condition:

> `when "derived-from-or-self(./equipment-augment:protocol-name, 'lldp:PROTOCOL_NAME_TYPE_LLDP')"`

This condition is never met because the model defines the relevant protocol name identity as `PROTOCOL_NAME_TYPE_PROTOCOL_NAME_TYPE_LLDP` (sic!).

**Comment by PrathibaJee** [comment]
UML2YANG tool included the when statement during the postprocessing , 
when "derived-from-or-self(./equipment-augment:protocol-name, 'lldp:PROTOCOL_NAME_TYPE_LLDP')"

which is not equal to the defined identity ,  PROTOCOL_NAME_TYPE_PROTOCOL_NAME_TYPE_LLDP.
Here , instead of modifying the when statement in the augment statement, the protocol name identity shall be modified 
from 
“PROTOCOL_NAME_TYPE_PROTOCOL_NAME_TYPE_LLDP” 
to 
“PROTOCOL_NAME_TYPE_LLDP” 

In the UML model , 
Enumeration name  is “ProtocolNameType”
EnumerationLiteral name is “PROTOCOL_NAME_TYPE_LLDP”
While generating the YANG, UML2YANG tool will formulate the identity name as follow, 
Enumeration name(converted to upper case snake case)  + “_”  + EnumerationLiteral name 
= “PROTOCOL_NAME_TYPE” + “\_” + “PROTOCOL_NAME_TYPE_LLDP”
= “PROTOCOL_NAME_TYPE_PROTOCOL_NAME_TYPE_LLDP”

**Proposal :**
In the UML model , EnumerationLiteral name shall be changed 
from 
“PROTOCOL_NAME_TYPE_LLDP” 
to 
“LLDP” 



<details>
<summary>
Side note (UML2YANG tool logic for other similar case)
</summary>
Why the identities are generated properly for  “LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER” ?

Regarding the “LAYER_PROTOCOL_NAME_TYPE identity” in technology specific modules, 
Inside the UML2YANG tool , apart from the core-model, for technology specific modules , there is a regular expression , 

```
var regex = /(layer.protocol.name.type|layer.protocol.name.type.layer.protocol.name.type|profile.name.type|profile.name.type.profile.name.type)/i;
```
UML2YANG tool is not creating typedef , identity statements for the enumeration that consists of this regex.
And in the post processing this is being taken care. 

In the post processing , 
For the technology specific modules, an identity for the layer-protocol-name-type is getting generated and attached , 
For example , for the air-interface , the identity and the when statement in the augment are included by the post processing script,

```
 identity LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER {
    base core-model:LAYER_PROTOCOL_NAME_TYPE;
    description
      "none";
  }

  augment "/core-model:control-construct/core-model:logical-termination-point/core-model:layer-protocol" {
    when "derived-from-or-self(./core-model:layer-protocol-name, 'air-interface:LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER')";
    uses air-interface-lp-spec;
    description
      "none";
  }

```

</details>

**Comment by openBackhaul** [comment]
Yes, I agree, the enumeration value is wrong in UML.
Created a [new UML (LLDP_1.0.0-tsi.230524.1420a.zip)](https://github.com/openBackhaul/lldp/blob/tsi/LLDP_1.0.0-tsi.230524.1420a.zip) and made it available.
